Description: drop test broken by pep479
Bug: https://github.com/cython/cython/issues/2454
--- a/tests/run/generators_py.py
+++ b/tests/run/generators_py.py
@@ -81,18 +81,6 @@ def with_outer(*args):
             yield i
     return generator
 
-def with_outer_raising(*args):
-    """
-    >>> x = with_outer_raising(1, 2, 3)
-    >>> list(x())
-    [1, 2, 3]
-    """
-    def generator():
-        for i in args:
-            yield i
-        raise StopIteration
-    return generator
-
 def test_close():
     """
     >>> x = test_close()
